### ISSUE TITLE
Support event and usage tracking

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/instructor-tools#238]
This is will include the following issue

- [x] Add support for Google Analytics #239
- [x] Add a local event log #240 
- [ ] Send events with Caliper?

**Comment by jonespm** [comment]
These tasks were implemented.
